# Generated by Django 5.1.3 on 2024-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='attorneys/', verbose_name='Foto de perfil'),
        ),
    ]
