# Generated by Django 5.1.3 on 2024-11-26 19:58

import fontawesome_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicearea',
            options={'ordering': ['id'], 'verbose_name': 'Área de Práctica', 'verbose_name_plural': 'Áreas de Práctica'},
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, help_text='Selecciona un ícono', max_length=60),
        ),
    ]
