# Generated by Django 5.1.3 on 2024-11-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('highlight_text', models.CharField(max_length=255, verbose_name='Texto Destacado')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Acerca de',
                'ordering': ['id'],
            },
        ),
    ]
