# Generated by Django 5.1.3 on 2024-11-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['id'], 'verbose_name': 'Acerca de', 'verbose_name_plural': 'Acerca de'},
        ),
    ]
