# Generated by Django 5.1.3 on 2024-11-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id'], 'verbose_name': 'Característica', 'verbose_name_plural': 'Características'},
        ),
    ]
