# Generated by Django 5.1.3 on 2024-12-11 02:23

import fontawesome_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome_5.fields.IconField(blank=True, help_text='Clase de Font Awesome', max_length=60, verbose_name='Icono')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('social_type', models.CharField(choices=[('social', 'Red Social'), ('phone', 'Teléfono'), ('email', 'Correo Electrónico')], help_text='Selecciona el tipo de contacto (Red Social, Teléfono o Correo Electrónico)', max_length=10, verbose_name='Tipo de Contacto')),
                ('social_value', models.CharField(help_text='URL, número de teléfono o correo electrónico', max_length=255, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['id'],
            },
        ),
    ]
